### ISSUE TITLE
求作者指教

### ISSUE THREAD

**Issue by bingely** [shenminjie/jd_tmall_refresh_demo#1]
if (ptrIndicator.getCurrentPercent() <= 1) {
                    mIvMan.setScaleX(ptrIndicator.getCurrentPercent());
                    mIvMan.setScaleY(ptrIndicator.getCurrentPercent());
                    mIvGoods.setScaleX(ptrIndicator.getCurrentPercent());
                    mIvGoods.setScaleY(ptrIndicator.getCurrentPercent());
                    int marginRight = (int) (MARGIN_RIGHT - MARGIN_RIGHT * ptrIndicator.getCurrentPercent());
                    mIvManLayoutParams.setMargins(0, 0, marginRight, 0);
                    mIvMan.setLayoutParams(mIvManLayoutParams);
                }
                if (ptrIndicator.getCurrentPercent() < 1.2) {
                    mTvRemind.setText("下拉刷新...");
                } else {
                    mTvRemind.setText("松开刷新...");
                }

其中 1  和 1.2是怎么计算的，为啥不是2或其他数字呢？

**Comment by shenminjie** [comment]
<ff_wms_rf.feifanzhixing.com.ffdmcpulltorefreshdemo.jd.JdRefreshLayout
        xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:id="@+id/test_recycler_view_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        cube_ptr:ptr_duration_to_close="100"
        cube_ptr:ptr_duration_to_close_header="500"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="2" >

        <android.support.v7.widget.RecyclerView
            android:id="@+id/test_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/white"/>
    </ff_wms_rf.feifanzhixing.com.ffdmcpulltorefreshdemo.jd.JdRefreshLayout>

cube_ptr:ptr_ratio_of_header_height_to_refresh  根据你设置下拉刷新高度的比例

**Comment by bingely** [comment]
谢谢
